<?php

namespace Proxies\__CG__\rj\StreamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class News extends \rj\StreamBundle\Entity\News implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'id', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'titre', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'description', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'date', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'image', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'auteur', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'tag1', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'tag2', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'tag3');
        }

        return array('__isInitialized__', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'id', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'titre', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'description', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'date', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'image', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'auteur', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'tag1', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'tag2', '' . "\0" . 'rj\\StreamBundle\\Entity\\News' . "\0" . 'tag3');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (News $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuteur($auteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuteur', array($auteur));

        return parent::setAuteur($auteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuteur', array());

        return parent::getAuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag($tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag', array($tag));

        return parent::setTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag', array());

        return parent::getTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag1($tag1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag1', array($tag1));

        return parent::setTag1($tag1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag1', array());

        return parent::getTag1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag2($tag2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag2', array($tag2));

        return parent::setTag2($tag2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag2', array());

        return parent::getTag2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag3($tag3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag3', array($tag3));

        return parent::setTag3($tag3);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag3', array());

        return parent::getTag3();
    }

}
